apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: dafang-exporter
  name: dafang-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dafang-exporter
  template:
    metadata:
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
      labels:
        app: dafang-exporter
    spec:
      containers:
      - image: radhus/dafang-exporter:latest
        imagePullPolicy: Always
        name: dafang-exporter
        ports:
        - containerPort: 9100
          name: exporter
          protocol: TCP
        command:
          - "/dafang-exporter"
          - "mqtt:1883"
          - "myhome/dafang"
      restartPolicy: Always
